<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <title>MyStockage</title>
  <!-- Feuilles de style externes -->
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <!-- Feuilles de style de l'application -->
  <link rel="stylesheet" href="css/style.css">
</head>

<body>
  <main id="main">
    <h1 class="title-main">MyStockage <i class="fas fa-database"></i></h1>
    <table class="stock-table">
      <thead>
        <tr class="head-col">
          <td>Nom du site</td>
          <td>Url du site</td>
          <td>Nom de la Base de données</td>
          <td>Espace utilisé</td>
          <td>En ligne</td>
          <td>Temps de réponse</td>
          <td>Action</td>
        </tr>
      </thead>
      <?php foreach ($sites as $site) { ?>
        <tr class="second-col <?= $site["Id"] ?>">
          <?php
          $check = $site["Site_Url"] . "/data";
          $header_response = get_headers($check, 1);
          //var_dump($header_response);
          if (strpos($header_response[0], "404") !== false || strpos($header_response[0], "301") !== false) { ?>
            <td><?= $site["Site_Name"] ?></td>
            <td><a href="<?= $site["Site_Url"] ?>" target="_blank"><?= $site["Site_Url"] ?></a></td>
            <td></td>
            <td></td>
          <?php } else if (strpos($header_response[0], "200") !== false) {
            $homepage = file_get_contents($site["Site_Url"] . "/data");
            //var_dump($homepage);
            echo $homepage;
          } ?>
          <td>
            <?= $site["Online"] ?>
          </td>
          <?php
          $ch = curl_init($site["Site_Url"]);
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
          if (curl_exec($ch)) {
            $info = curl_getinfo($ch); ?>
            <td> <?= $info['total_time'] ?>s</td>
          <?php } else {
            $info = curl_getinfo($ch); ?>
            <td> <?= $info['total_time'] ?>s</td>
          <?php }
          curl_close($ch); ?>
          <td><a href="modify.php?id=<?= $site["Id"] ?>"><button><i class="fas fa-pen"></i></button>
              <a href="delete.php?id=<?= $site["Id"] ?>"><button><i class="fas fa-trash-alt"></i></button></td>
        </tr>
      <?php } ?>
    </table>
    <button class="btn btn-2 btn-2a"><span>Ajouter un site</span></button>
    <form action="index.php" method="post" class="form hidden">
      <label for="name">Nom du site</label>
      <input type="text" name="name" id="name" required>
      <label for="url">Url du site</label>
      <input type="text" name="url" id="url" value="http://" required>
      <label for="bdd">Mot de passe base de données</label>
      <input type="text" name="bdd" id="bdd" required>
      <!-- <label for="get">Nom du site (sans espace)</label>
      <input type="text" name="get" id="get" required> -->
      <input type="submit" name="submit" id="submit" value="Valider" required>
    </form>
  </main>
  <script src="js/main.js"></script>
</body>

</html>