<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>MyStockage</title>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <main>
        <?php if ($error !== null) { ?>
            <p><?= $error ?></p>
        <?php } ?>

        <form action="login.php" method="POST">
            <input type="text" name="name" placeholder="name" />
            <input type="password" name="password" placeholder="password" />
            <input type="submit" value="connexion" />
        </form>
    </main>
</body>

</html> -->