<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>MyStockage</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <main>

        <form action="register.php" method="POST">
            <input type="text" name="name" placeholder="firstName" />
            <input type="text" name="password" placeholder="password" />
            <input type="submit" value="Submit" />
        </form>

    </main>
</body>

</html>